# Generated by Django 6.0.1 on 2026-01-16 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Тип устройства')),
                ('code', models.SlugField(help_text='Внутренний идентификатор (phone, laptop, monitor, ...)', unique=True, verbose_name='Код типа')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Тип устройства',
                'verbose_name_plural': 'Типы устройств',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='Серийный номер')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Дата покупки')),
                ('is_active', models.BooleanField(default=True, verbose_name='В эксплуатации')),
                ('condition', models.CharField(choices=[('new', 'Новое'), ('good', 'Хорошее'), ('satisfactory', 'Удовлетворительное'), ('needs_repair', 'Требуется ремонт'), ('written_off', 'Списано')], default='good', max_length=20, verbose_name='Состояние')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='device.devicetype', verbose_name='Тип устройства')),
            ],
            options={
                'verbose_name': 'Устройство',
                'verbose_name_plural': 'Устройства',
            },
        ),
    ]
